sources:
  - name: raw
    description: Raw taxi trip data from NYC TLC
    database: dtc-de-course-485513
    schema: zoomcamp
    tables:
      - name: green_tripdata
        description: Raw green taxi trip records
      - name: yellow_tripdata
        description: Raw yellow taxi trip records
